name: test-container-job
on: workflow_dispatch
jobs:
  # this sucks. can't checkout repo then invoke container with volume of
  # repo. so:
  # - checkout repo
  # - docker run with volume mounts input/output directories
  # - docker moves files to output directory so this script is ignorant of dir structure
  # - this script collects built files

  build:
    strategy:
      matrix:
        image: [centos7, linux-arm64, alpine]
    name: Building ${{ matrix.image }} binaries
    runs-on: ubuntu-latest

    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 20
      # - name: Install dependencies
      #   run: npm install

      - name: Build binaries
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo -w /repo ghcr.io/contrast-security-oss/${{ matrix.image }}:latest
      - name: Show files
        run: find ${{ github.workspace }}
